name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # once per month
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update
        id: update
        run: |
          pip install tox
          tox -e py
      - name: Commit files
        if: steps.update.outputs.RHEA_UPDATED != 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "⚗️ Update to version ${{ steps.update.outputs.RHEA_UPDATED }}" -a
      - name: Push changes
        if: steps.update.outputs.RHEA_UPDATED != 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
